on:
  push:
    branches:
      - main

jobs:
  build_and_tag:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [3.9] # You can adjust this

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to fetch all history for tags
          
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Get version and set env
        id: get_version
        run: |
          VERSION=$(python -W ignore utils.py --version)
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          if [ -z "$VERSION" ]; then
            echo "Error: Version was not set!"
            exit 1
          fi

      - name: Create Git tag
        if: ${{ github.ref == 'refs/heads/main' }} # Only tag on pushes to main
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag "v${VERSION}" # Use the version from the script
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}

      - name: Build executable (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          # Include the version in the executable name
          python -m PyInstaller --onefile --name "vcdech-v${{ env.VERSION }}-win" utils.py

      - name: Build executable (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          # Include the version in the executable name
          python -m PyInstaller --onefile --name "vcdech-v${{ env.VERSION }}-linux" utils.py

      - name: Build executable (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          # Include the version in the executable name
          python -m PyInstaller --onefile --name "vcdech-v${{ env.VERSION }}-mac" utils.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vcdech-v${{ env.VERSION }}-${{ matrix.os }}
          path: ${{ steps.build_executable.outputs.EXECUTABLE_PATH }} # Correctly use the output from the build step
          if-no-files: error

      - name: Create Release
        if: ${{ github.ref == 'refs/heads/main' }} # important, only for main branch
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.VERSION }}"
          name: "vcdech v${{ env.VERSION }}"
          body: |
            Release of vcdech version ${{ env.VERSION }}.
            Includes executables for Windows, Linux, and macOS.
          files: |
            dist/vcdech-v${{ env.VERSION }}-win.exe
            dist/vcdech-v${{ env.VERSION }}-linux
            dist/vcdech-v${{ env.VERSION }}-mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

